### ISSUE TITLE
query fails silently on parse errors

### ISSUE THREAD

**Issue by luntain** [maoe/influxdb-haskell#64]
I came across it when using `(Tagged "time" Int)` field. The query was returning no results even though printed and ran by hand was ok. It worked when I changed it to `Tagged "time" UTCTime`. But it broke agains when I set the precision to `Second` in query parameters.  Now I know that was due to the precision being set to `rfc3339` which returns human readable timestamps. Anyway, the bigger issue here is that parse errors are silent failures.

**Comment by maoe** [comment]
This is because the `QueryResults` instance for that type uses `parseResults` which in turn uses the `lenientDecoder`.

It might be better to default to the `strictDecoder`, or maybe modify the method to take the decoder so that the user can choose whichever s/he like.

**Comment by maoe** [comment]
I've fixed the issue in the [feature/error-handling](https://github.com/maoe/influxdb-haskell/blob/feature/error-handling/) branch. Could you confirm if [case_issue64](https://github.com/maoe/influxdb-haskell/blob/0ae4b2ea425c1558f136a286ec38f6b68e9d0cbf/tests/regression-tests.hs#L22-L42) is the issue you described and check if it's fixed in this branch?
