### ISSUE TITLE
Invalid query failure suppressed

### ISSUE THREAD

**Issue by luntain** [maoe/influxdb-haskell#66]
`select time from measurement` is an invalid query, because "at least one non-time field must be querried", but you won't get this error through the lib because it just silently returns an empty result. I got that error when running the query in the cli.

**Comment by maoe** [comment]
I've fixed the issue in the [feature/error-handling](https://github.com/maoe/influxdb-haskell/blob/feature/error-handling/) branch. Could you confirm if [case_issue66](https://github.com/maoe/influxdb-haskell/blob/0ae4b2ea425c1558f136a286ec38f6b68e9d0cbf/tests/regression-tests.hs#L45-L58) is the issue you described and check if it's fixed in this branch?

**Comment by luntain** [comment]
Thanks for fixing it. The errors are no longer suppressed. There is a regression. There is an exception thrown for empty result set.

`*** Exception: UnexpectedResponse "BUG: key \"series\" not present in Database.InfluxDB.Query.query"`

**Comment by maoe** [comment]
Force pushed a change. Could you try again?

**Comment by luntain** [comment]
All good.

**Comment by maoe** [comment]
Thanks for checking. I'll fix some comments, implement #67, check if it works on our code base, then release.
